### ISSUE TITLE
Bug: Copy Paste button for code snippets adds extra line per new line in code

### ISSUE THREAD

**Issue by msdolbey** [mesosphere/d2iq-engineering-blog#92]
If I go to a blog post that has a code snippet
And I hit the copy button that is nested in the code snippet in the blog post
And I paste that any where, 
It will add a new line for every line that's in the code.

Example: 
https://eng.d2iq.com/blog/profiling-kubernetes-controllers-with-pprof/

If you go to the first code snippet, and use the copy button and paste it somewhere, it looks like this:

```bash
goroutine    - stack traces of all current goroutines

heap         - a sampling of memory allocations of live objects

allocs       - a sampling of all past memory allocations

threadcreate - stack traces that led to the creation of new OS threads

block        - stack traces that led to blocking on synchronization primitives

mutex        - stack traces of holders of contended mutexes

```

However, it should look like this:

```bash
goroutine    - stack traces of all current goroutines
heap         - a sampling of memory allocations of live objects
allocs       - a sampling of all past memory allocations
threadcreate - stack traces that led to the creation of new OS threads
block        - stack traces that led to blocking on synchronization primitives
mutex        - stack traces of holders of contended mutexes
```

Browser: Chrome 116
OS: Mac OSX Ventura 13.1

**Comment by jimmidyson** [comment]
@msdolbey Could you please test out #93 (preview at https://deploy-preview-93--d2iq-engineering.netlify.app/)?
